name: Build and release apk

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build APK
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug
        mv ./app/build/outputs/apk/debug/app-debug.apk ${{ github.event.repository.name }}.apk

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      env:
        GOOGLE_CLIENT_ID: ${{ vars.GOOGLE_CLIENT_ID }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        title: ${{ github.event.repository.name }} v${{ github.run_number }}
        automatic_release_tag: ${{ github.run_number }}
        prerelease: false
        files: |
          *.apk
